### ISSUE TITLE
repository name and host your webpage

### ISSUE THREAD

**Issue by mkruijt** [moesi88/HTML-and-CSS-#1]
Hi Mo,

Can you rename your repository in "hyf-html-css" or just name it "html-css"
It is better to avoid capital letters.

Also can you check again on how to host your website via Github?
You can read that here: https://github.com/HackYourFuture/HTML-CSS/blob/master/Week1/MAKEME.md
And if you already did this put the link to your page in the readme file.

**Comment by moesi88** [comment]
done
